image: node:latest
cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - yarn install --progress=false
    - yarn build

test:
  stage: test
  script:
    - yarn install --progress=false
    - yarn test:unit
    - yarn lint

pages:
  stage: deploy
  dependencies:
    - build
    - test
  before_script:
    - echo "VUE_APP_BASE_ROUTE=/$PROJECT_NAME/" >> .env.local
    - echo "VUE_APP_OMDB_KEY=$API_OMDB_KEY" >> .env.local
  script:
    - yarn build
    - mv public public-vue
    - mv dist public

  artifacts:
    expire_in: 1 week
    paths:
      - public
  only:
    - master
