name: Deploy to GitHub Pages
on:
  schedule:
    - cron: '0 3 * * *' # run at 2 AM UTC
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        npm install
        npm run-script build
